export const SEARCH_CHANGE = 'SEARCH_CHANGE'

export const MOVIES_FETCHED = 'MOVIES_FETCHED'
export const MOVIES_FAILED = 'MOVIES_FAILED'
export const MOVIES_ADDITIONAL = 'MOVIES_ADDITIONAL'
export const MOVIES_DETAILS = 'MOVIES_DETAILS'

export const FAVORITES_ADD = 'FAVORITES_ADD'
export const FAVORITES_DELETE = 'FAVORITES_DELETE'
export const FAVORITES_LIST= 'FAVORITES_LIST'